# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jd_live_lottery_social

on:
    workflow_dispatch:
    schedule:
        - cron: "0 7-23/1 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_live_lottery_social

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: 安装依赖包
              run: |
                  npm install
            - name: "运行【jd_live_lottery_social】"
              run: |
                  node onlyOneExecute.js
              env:
                  JD_COOKIE: ${{ secrets.JD_COOKIE }}
                  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
                  PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}
                  IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
                  QYWX_KEY: ${{ secrets.QYWX_KEY }}
                  QYWX_AM: ${{ secrets.QYWX_AM }}
                  JD_DEBUG: ${{ secrets.JD_DEBUG }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
                  SYNCURL: https://raw.githubusercontent.com/ElsaKing/DogDog/main/jd_live_lottery_social.js
