name: sngxpro-sync
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync sngxpro_quanx
        uses: cyz0105/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/sngxpro/QuanX.git"
          source_branch: "master"
          destination_branch: "sngxpro_quanx"
          github_token: ${{ secrets.PAT }}
